### ISSUE TITLE
Proposal: remove unnesessary headers

### ISSUE THREAD

**Issue by undiabler** [dharrigan/mkinitcpio-wireguard#1]
Big license headers in config files are unwanted.

When you've already installed package there is no need to watch every time that config files and hooks are unlicensed.
My proposal is to remove this headers, but copy LICENSE file with its content to `/usr/share/licenses/$pkgname/LICENSE` as many packages do.

**Comment by dharrigan** [comment]
Agreed! Great idea. Will do!

**Comment by dharrigan** [comment]
Done.
