### ISSUE TITLE
Why making the interface behave like a client?

### ISSUE THREAD

**Issue by AlphaJack** [dharrigan/mkinitcpio-wireguard#3]
Hi, first of all thank you for this little but fantastic hook!
In order to make it work, I needed to dig in the code and give a look around, modifying a pair of things.

I can't understand the major design choice: why does this WireGuard interface behave more like a client than a server? I know they don't use these terms since they are both peers, but there are small differences in the two configurations.

What I call a client expects a host with a specific IP and port (PEER_ENDPOINT); a server instead has to bind to a specific port (LISTEN_PORT) in order to receive connections there.

TinySSH for instance binds to port 22, so authorized clients can connect to SERVER_IP:22.
I expect Wireguard to behave similarly by binding to a specific port of my choice, e.g 51820, allowing authorized clients to connect to SERVER_IP:51820.

---

In my hook I now have:

```bash
[...]
    ip link add dev $INTERFACE type wireguard
    wg set $INTERFACE \
        listen-port $LISTEN_PORT \
        private-key $PRIVATE_KEYFILE \
        peer $PEER_PUBLIC_KEY \
        persistent-keepalive $PERSISTENT_KEEPALIVES \
        allowed-ips $ALLOWED_IPS
        #endpoint $PEER_ENDPOINT \
    ip addr add $INTERFACE_ADDR dev $INTERFACE
[...]
```

Of course I also added a `LISTEN_PORT=` directive to the "unlock" configuration file.

The resulting configuration should be equivalent to the following:

Encrypted server:
```ini
[Interface]
# Encrypted server
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = SERVER_PRIVATE_KEY

[Peer]
# Decrypting client
PublicKey = CLIENT_PUBLIC_KEY
AllowedIPs = 10.0.0.2/32
PersistentKeepalive = 25
```

Decrypting client:
```ini
[Interface]
# Decrypting client
Address = 10.0.0.2/32
PrivateKey = CLIENT_PRIVATE_KEY

[Peer]
# Encrypted server
Endpoint = example.org:51820
AllowedIPs = 10.0.0.0/24
PublicKey = SERVER_PUBLIC_KEY
PersistentKeepalive = 25
```

Example:
Server has 192.168.1.150 as LAN address, while the client is in another netwok and has 172.0.0.10 as local address

 - Day 1:  server listens to 0.0.0.0:51820, clients connects to example.org:51820 with an interface address of 172.0.0.10:34873
 - Day 2:  server listens to 0.0.0.0:51820, clients connects to example.org:51820 with an interface address of 172.0.0.10:48120
 - Day 3: everything keep working fine, the server continues to not giving a dime about the client endpoint
---

Instead with the package default configuration it kinda looked like this:

Encrypted server:
```ini
[Interface]
# Encrypted server
Address = 10.0.0.1/24
PrivateKey = SERVER_PRIVATE_KEY

[Peer]
# Decrypting client
PublicKey = CLIENT_PUBLIC_KEY
AllowedIPs = 10.0.0.2/32
# how am I supposed to know my client address and the port it is using?
Endpoint = ??????
PersistentKeepalive = 25
```

Decrypting client:
```ini
# I have no idea of how your client should look like
```

Example:
Server has 192.168.1.150 as LAN address, while the client is in another netwok and has 172.0.0.10 as local address

 - Day 1:  server binds to 192.168.1.150:54223 trying to connect to the clients IP (but how can it find the public address of th 172.0.0.0/24 network gateway?). What if there is no port forwarding pointing to the client for port (let's suppose) 51820? What address should the client use as its endpoint? Should he guess example.org:54223? Who put a forward rule for that port in the network 192.168.1.0/24?
 - Day 2: server binds to 192.168.1.150:23516 trying to connect to the clients IP...

**Comment by alerque** [comment]
I can't speak for the author, but client mode makes *far* more sense for my situation. I need to unlock root drives on boot for several machines that are behind NAT devices with unpredictable IPs. By having them login to my wireguard server elsewhere all I need to do to "find" them is use any other connected client to reach them directly. If I had to disconnect the system I was using from it's current client connection and connect directly to the booting device I would ⓐ need to know the dynamic IP‌ address it was behind, ⓑ have a DMZ or port forward working for it, and ⓒ leave my client vulnerable in the mean time while I switched networks.

**Comment by dharrigan** [comment]
Hi,

@alerque is absolutely correct. It is designed to act as a client, not a "server", in the sense that Wireguard is a peer network and doesn't really have a concept of a "server", although one can nominate a node to be the rendevouz (for bridging to another network, like ppp0 for example).

All of the machines with `mkinitcpio-wireguard` installed are behind NAT'ed firewalls (like @alerque ) and there is no way the ports are going to be opened up and exposed to allow for binding.

All I have to do, is reboot one of the machines, wait a few moments for it to come back with the wireguard interface up - whilst I'm pinging the well-known IP address of the machine. Then, once the ping's are being replied to, I know I can ssh to the machine (on the wireguard IP address) and unlock. Simples!

**Comment by AlphaJack** [comment]
Thank you, it makes much more sense now.
The fact is that it is my only server and therefore I lack a known endpoint where this device can meet with others.
What do you think about adding the listen port variable to the configuration, making it and the peer endpoint optional arguments for two different use cases?

**Comment by dharrigan** [comment]
Hi,

Thank you for your helpful feedback. I'll ponder upon it. A suggestion would be to spin up a very low cost VM somewhere (maybe on AWS, Digital Ocean, or the numerous others out there) to act as the "hub", then by sshing into this VM (which is running Wireguard) you can hop over to your server and unlock (or do a proxy jump to directly hop over to your server).

I will of course also consider pull requests :-)

-=david=-

**Comment by alerque** [comment]
An option to open up a port and act as a host would be fine as long as it was off by default ;-)

**Comment by AlphaJack** [comment]
In the meanwhile I think we can close this issue as you have already answered to my original question
